// DESCRIPTION: Verilator: Verilog Test module
//
// Second counter-example showing that gating SYNCASYNCNET on
// AstNodeIf::isBoundsCheck() also silently suppresses the warning for a
// genuine bounds-check If generated by V3Unknown (BOUNDLVALUE), not just
// for assertion-related Ifs from V3Assert -- this time reproducible with
// *no* special flags at all (unlike t_boundscheck_syncasync_counterexample,
// which needs -fno-split to keep V3Unknown's bounds-check If from being
// rebuilt, without its isBoundsCheck() flag, by an unrelated gap in
// V3Split).
//
// The trick here is a locally-computed index (idx_r, assigned with a
// blocking '=' from the primary-input idx) instead of using the primary
// input directly as the array index. Because idx_r is both written and
// read inside this always block, V3Split's dependency graph keeps the
// bounds-check If connected to the array-write statement it wraps, so
// V3Split never decides to split this block at all -- the If, with its
// isBoundsCheck() flag, reaches V3Gate completely unmodified even with
// default flags.
//
// isBoundsCheck() is set true by both producers (V3Assert/V3AssertNfa for
// assertions, V3Unknown for real array-bounds checks), so a Gate-stage
// check that only looks at that flag cannot tell "underneath an assertion"
// apart from "underneath a real array-bounds-check", and would wrongly
// drop this warning for real hardware.
//
// This file ONLY is placed under the Creative Commons Public Domain.
// SPDX-License-Identifier: CC0-1.0

module t (
    input clk,
    input rst_both_l,
    input [2:0] idx,
    input d
);

  // Non-power-of-2 sized array: a 3-bit index (0-7) can exceed the
  // declared range (0-4), so V3Unknown cannot statically prove the index
  // is always in bounds and must insert a runtime bounds-check If.
  reg [7:0] mem[0:4];
  reg [2:0] idx_r;
  reg q3;

  // rst_both_l used as ASYNC reset here
  always @(posedge clk or negedge rst_both_l) begin
    if (~rst_both_l) q3 <= 1'b0;
    else q3 <= d;
  end

  // rst_both_l also used SYNCHRONOUSLY here, as data feeding a
  // variable-index (out-of-range-possible) memory write. V3Unknown wraps
  // this whole statement in an AstIf with isBoundsCheck(true) to guard
  // the out-of-range index -- nothing to do with assertions. idx_r is
  // computed locally (blocking assign) so that V3Split's data-dependency
  // graph keeps this If bundled with the write it guards, and never
  // splits this block, even under default flags.
  always @(posedge clk) begin
    idx_r = idx;
    mem[idx_r] <= rst_both_l ? d : 1'b0;
  end

endmodule
